import { IoMdThumbsDown, IoMdThumbsUp } from "react-icons/io";
import { RiRobot2Line } from "react-icons/ri";
import { motion } from "framer-motion";

interface AutoGeneratedTrainerProps {
  label?: string;
  labelStyle?: React.CSSProperties;
  tailwindClasses?: string;
}

const AutoGeneratedTrainer: React.FC<AutoGeneratedTrainerProps> = ({
  label,
  labelStyle,
  tailwindClasses,
}) => {
  return (
    <>
      <div className="flex">
        <div className="bg-neutral-200 py-1 lg:py-2 px-3 lg:px-5 rounded-full inline">
          <div className="flex space-x-2 items-center">
            <RiRobot2Line className="h-[20px] w-[20px] lg:h-[25px] lg:w-[25px] bg-secondary-light p-[3px] lg:p-[5px] text-white rounded-2xl" />
            <div
              style={labelStyle}
              className={`${tailwindClasses} my-auto text-sm lg:text-base`}
            >
              {label}
            </div>
            <motion.button whileHover={{ scale: 1.2 }}>
              <IoMdThumbsUp className="m-auto h-[20px] w-[20px] lg:h-[25px] lg:w-[25px] text-label" />
            </motion.button>
            <motion.button whileHover={{ scale: 1.2 }}>
              <IoMdThumbsDown className="m-auto h-[20px] w-[20px] lg:h-[25px] lg:w-[25px] text-label" />
            </motion.button>
          </div>
        </div>
      </div>
    </>
  );
};

export default AutoGeneratedTrainer;
