import { RiRobot2Line } from "react-icons/ri";

const CreatedByGPT: React.FC = () => {
  return (
    <div>
      <div className="flex items-center py-2">
        <RiRobot2Line className="h-[25px] w-[25px] bg-secondary-light p-[5px] text-white rounded-2xl mr-[5px]" />
        <div className="text-sm italic">Generated by BarTender GPT</div>
      </div>
    </div>
  );
};

export default CreatedByGPT;
