import AutoGeneratedTrainer from "./AutoGeneratedTrainer";

interface GPTTrainerProps {
  label?: string;
  labelStyle?: React.CSSProperties;
  tailwindClasses?: string;
}

const GPTTrainer: React.FC<GPTTrainerProps> = ({
  labelStyle,
  tailwindClasses,
}) => {
  return (
    <AutoGeneratedTrainer
      label="BarTender GPT"
      labelStyle={labelStyle}
      tailwindClasses={`${tailwindClasses} italic`}
    />
  );
};

export default GPTTrainer;
